### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ashpriom** [robert-bor/aho-corasick#13]
Hi Mr. Robert,

I'm trying to implement your code. I put the following dependency - 		
         
        <dependency>
        	<groupId>org.ahocorasick</groupId>
        	<artifactId>ahocorasick</artifactId>
        	<version>0.2.4</version>
    	</dependency>

I'm getting the following error on mvn install-

<pre>priom@ASUS-S551LA:~/Public/6461/aho$ mvn -e install
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.ahocorasick:ahocorasick'}' and 'Vertex{label='org.ahocorasick:ahocorasick'}' introduces to cycle in the graph org.ahocorasick:ahocorasick --> org.ahocorasick:ahocorasick
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.ahocorasick:ahocorasick'}' and 'Vertex{label='org.ahocorasick:ahocorasick'}' introduces to cycle in the graph org.ahocorasick:ahocorasick --> org.ahocorasick:ahocorasick
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:295)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: hidden.org.codehaus.plexus.util.dag.CycleDetectedException: Edge between 'Vertex{label='org.ahocorasick:ahocorasick'}' and 'Vertex{label='org.ahocorasick:ahocorasick'}' introduces to cycle in the graph org.ahocorasick:ahocorasick --> org.ahocorasick:ahocorasick
	at hidden.org.codehaus.plexus.util.dag.DAG.addEdge(DAG.java:143)
	at hidden.org.codehaus.plexus.util.dag.DAG.addEdge(DAG.java:123)
	at org.apache.maven.project.ProjectSorter.<init>(ProjectSorter.java:118)
	at org.apache.maven.execution.ReactorManager.<init>(ReactorManager.java:99)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:288)
	... 11 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: Less than 1 second
[INFO] Finished at: Thu Sep 25 01:00:02 EDT 2014
[INFO] Final Memory: 2M/61M
[INFO] ------------------------------------------------------------------------ 

</pre>

<p>Can you help? Can it be a version issue? I am using-

Apache Maven 2.2.1 (rdebian-14)
Java version: 1.7.0_65

Thanks, really appreciate your work!</p>

**Comment by robert-bor** [comment]
Check the unit tests, particularly TrieTest.java. It contains a number of examples that you can run yourself to see them work.

**Comment by ashpriom** [comment]
I understand Mr. Robert. Thank you.
Best regards,

Syed


Sincerely,
Syed Ashfaque Uddin Priom
ashpriom.com
--------------------------
